// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newTest.proto

package my.suveng.grpc.two.api;

public interface MyRequestTwoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyRequestTwo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
