### 1. 获取授权码 需要浏览器访问 拉起登录页

GET http://localhost:8080/oauth/authorize?client_id=client&response_type=code


### 2. 获取token 替换code为浏览器返回的code

POST http://client:secret@localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=owNsev
