# 自定义配置
oauth:
  jdbc-url: jdbc:mysql://192.168.9.234:3306/ss?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull
  user: root
  password: 123456
  jdbc-driver-class: com.mysql.jdbc.Driver
#security:
#  user:
#    name: username
#    password: password
