// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newTest.proto

package my.suveng.grpc.two.api;

public interface MyResponseTwoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyResponseTwo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   * @return The realname.
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 2;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
