// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newTest.proto

package my.suveng.grpc.two.api;

public final class StudentTwo {
  private StudentTwo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyRequestTwo_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyRequestTwo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyResponseTwo_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyResponseTwo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnewTest.proto\" \n\014MyRequestTwo\022\020\n\010usern" +
      "ame\030\001 \001(\t\"!\n\rMyResponseTwo\022\020\n\010realname\030\002" +
      " \001(\t2\226\002\n\021StudentServiceTwo\0226\n\025getRealNam" +
      "eByUsername\022\r.MyRequestTwo\032\016.MyResponseT" +
      "wo\022A\n\036getRealNameByUsernameResStream\022\r.M" +
      "yRequestTwo\032\016.MyResponseTwo0\001\022A\n\036getReal" +
      "NameByUsernameReqStream\022\r.MyRequestTwo\032\016" +
      ".MyResponseTwo(\001\022C\n\036getRealNameByUsernam" +
      "eStreamAll\022\r.MyRequestTwo\032\016.MyResponseTw" +
      "o(\0010\001B&\n\026my.suveng.grpc.two.apiB\nStudent" +
      "TwoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MyRequestTwo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyRequestTwo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyRequestTwo_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_MyResponseTwo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MyResponseTwo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyResponseTwo_descriptor,
        new java.lang.String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
