spring:
  application:
    name: istio-cloud-pay-demo
  zipkin:
    base-url: http://192.168.9.208:9411
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true
management:
  server:
    port: 28081
server:
  port: 28080
grpc:
  server:
    port: 29090
  client:
    order:
      address: 'static://127.0.0.1:19090' # rpc服务的地址
      negotiation-type: plaintext
    user:
      address: 'static://127.0.0.1:39090' # rpc服务的地址
      negotiation-type: plaintext
