spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 2
      max-active: 10
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 50000
      max-wait: 500
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: me,config,stat,wall,slf4j
      connect-properties: {"druid.stat.mergeSql":true,"druid.stat.slowSqlMillis":5000} # 慢SQL查询
      # 让连接池知道数据库已经断开了，并且自动测试连接查询
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filter:
        me:
          hello: weewewew
          user: wewewewe
  jpa:
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 事务引擎
    hibernate:
      ddl-auto: create
