// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package my.suveng.grpcdemomaven.grpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   * @return The realname.
   */
  String getRealname();
  /**
   * <code>string realname = 2;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
