// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package my.suveng.grpcdemomaven.grpc;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
